# Generated by Django 2.2.24 on 2021-07-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze', models.ManyToManyField(blank=True, related_name='_winner_bronze_+', to='sports.Athlete')),
                ('gold', models.ManyToManyField(blank=True, related_name='_winner_gold_+', to='sports.Athlete')),
                ('silver', models.ManyToManyField(blank=True, related_name='_winner_silver_+', to='sports.Athlete')),
                ('sport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport+', to='sports.Sport')),
            ],
            options={
                'verbose_name': 'Winner',
                'verbose_name_plural': 'Winners',
            },
        ),
    ]
