# Generated by Django 2.2.24 on 2021-07-12 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20210712_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='bronze',
        ),
        migrations.AddField(
            model_name='sport',
            name='bronze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze+', to='sports.Athlete'),
        ),
        migrations.RemoveField(
            model_name='sport',
            name='gold',
        ),
        migrations.AddField(
            model_name='sport',
            name='gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold+', to='sports.Athlete'),
        ),
        migrations.RemoveField(
            model_name='sport',
            name='silver',
        ),
        migrations.AddField(
            model_name='sport',
            name='silver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver+', to='sports.Athlete'),
        ),
    ]
