# Generated by Django 2.2.24 on 2021-09-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesses',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
