# Generated by Django 2.2.24 on 2022-01-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extended_user',
            name='email',
        ),
    ]
