# Generated by Django 2.2.24 on 2022-01-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_extended_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended_user',
            name='use_full_name',
            field=models.BooleanField(default=False),
        ),
    ]
